development:
  adapter: postgresql
  encoding: unicode
  database: ryanodonnell_development
  pool: 5
  username: ryanodonnell
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ryanodonnell_test
  pool: 5
  username: ryanodonnell
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ryanodonnell_production
  pool: 5
  username: ryanodonnell
  password:
